### ISSUE TITLE
Application failed to start on Windows

### ISSUE THREAD

**Issue by tanrak** [danpla/dpscreenocr#1]
I get the following error when starting the program (ZIP-Version):

![dpscreenocr](https://user-images.githubusercontent.com/35105392/59833550-8df2bc80-9346-11e9-9137-2533b3964b32.png)

**Comment by danpla** [comment]
I'll fix this soon.

Can you tell what Windows version are you using?

**Comment by tanrak** [comment]
Windows 10 Pro 1803

**Comment by danpla** [comment]
Please test the following build:

https://drive.google.com/open?id=1zU2Qst6dRWiMXFYBXZ2p5QOmvwIAnG5x

**Comment by tanrak** [comment]
This build works. Thanks.

**Comment by danpla** [comment]
Thank you for the bug report. I will soon create new release builds and update the website links.

**Comment by danpla** [comment]
You can now download v1.0.2 at https://danpla.github.io/dpscreenocr/.

**Comment by tanrak** [comment]
That was quick. Thanks again.

**Comment by danpla** [comment]
You're welcome.
