### ISSUE TITLE
Does not save configs on Windows

### ISSUE THREAD

**Issue by toprak** [danpla/dpscreenocr#12]
Hi, I was using it on Ubuntu without any problem but on Windows it does not save config when reboot computer. I just created shortcut of dpscreenocr.exe and copied it to `C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup` to make dpscreenocr show up on system startup, but yeah it does not save configs.
I use Windows 7, eng ocr, by the way, What split text blocks option does?

**Comment by danpla** [comment]
Hi. I can't reproduce the issue on my Windows 7: like on Linux, rebooting, logging out, or shutting down results in closing the main window, which is in turn saves the settings (the state of checkboxes, window size and position, etc.) and history.

What is your Windows version?
***
The "Split text blocks" option splits independent text blocks, like columns. There's a picture in the manual that demonstrates how this works:
https://danpla.github.io/dpscreenocr/manual.html#split-text-blocks

**Comment by toprak** [comment]
I dont know why but it saves configs somehow. Thanks for your help.
