### ISSUE TITLE
Tray icon mode?

### ISSUE THREAD

**Issue by abhijit-hota** [danpla/dpscreenocr#15]
I really love the program and am using it more than I thought I'd. Thank you!

However, I had a feature request: **run in the background (preferably as a tray icon)**.

**Comment by danpla** [comment]
I'm glad that the program is useful for you.

The tray icon is already implemented and will be available in the next release: #6

**Comment by abhijit-hota** [comment]
Oh, my bad. I must have missed among the previous issues while searching for a possible duplicate. Glad it's already addressed!

Any potential release date? Thanks for clarifying.

**Comment by danpla** [comment]
There's no particular date for now; probably this year or early next.
