### ISSUE TITLE
No languages detected due to TESSDATA_PREFIX

### ISSUE THREAD

**Issue by ainal-3fresources** [danpla/dpscreenocr#16]
Application was running previously but after 
1. a windows update and 
2. uninstallation of a local installation of tessaract (which was installed before dpscreenocr), 

the application opens with the message, "Please install languages" . Assumed that no language file was installed or missing. Upon inspection,  the file eng.traindata was present in the C:\Program Files (x86)\dpScreenOCR\tessdata directory. Downloading another language file and copying it to the same directory does not change the error message. 

Removed and re-installed dpscreenocr several times did not yield different results. Uninstalling dpscreenocr does not remove the configuration file in  C:\Users\<user>\AppData\Local\dpscreenocr. Manually deleted the directory and re-installed dpscreenocr but still no change. 
Installation onto another computer with similar windows level (version 20H2 Build 19042.1466) was successful so issue is local to the computer. 
Does dpscreenOCR aware of other tesseract installation through environment variables?

**Comment by danpla** [comment]
Most likely, the Tesseract installer has left the TESSDATA_PREFIX environment variable, so removing it manually should help.

dpScreenOCR currently doesn't prevent the tesseract library to use TESSDATA_PREFIX.

**Comment by ainal-3fresources** [comment]
Removed the TESSDATA_PREFIX environment variable, rebooted and it works ok now. Thank you for a very handy application.

**Comment by danpla** [comment]
You're welcome.

**Comment by joneldiablo** [comment]
hi!!!!
I having the same problem on linux. dpscreenocr was working ok but after I install tesseract-ocr-spa lang, then dpscreenocr not work anymore. What could I do?
I have install again tesseract uninstall lang, reinstall, nothings work

**Comment by danpla** [comment]
Since version 1.1.0, dpScreenOCR for Windows will use an explicit data path (`C:\Users\(your name)\AppData\Local\dpscreenocr\tesseract_data`) instead of `tessdata` in the directory of EXE. Thus, the program will no longer be affected by TESSDATA_PREFIX.
