### ISSUE TITLE
Can't use the app for windows opened after I launched dpscreenocr

### ISSUE THREAD

**Issue by Kirinko** [danpla/dpscreenocr#17]
Hello!
I have very annoying issue with dpscreenocr. It's supper nice program, but if I open new windows, i. e. some PDF, after I launched dpscreenocr, then nothing can be done to ocr the content of new window, because dpscreenocr's box shows up behind window I need. 

I use Linux, X11 with qtile DE.

**Comment by danpla** [comment]
Hello,

I added a workaround that basically pushes the selection on top of the window stack. As of version 0.21.0, qtile doesn't seem to support the flags that tell a window manager to always keep a window on top.
