### ISSUE TITLE
App doesn't see languages on Mint 20.2

### ISSUE THREAD

**Issue by joneldiablo** [danpla/dpscreenocr#18]
I have this error
qt5ct: using qt5ct plugin
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!

but /usr/share/tesseract-ocr/5/tessdata/eng.traineddata is the new one

error from  linux mint

**Comment by danpla** [comment]
I was unable to reproduce the issue on Linux Mint 20.2. The `tesseract-ocr-eng` package provides `/usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata`, and dpScreenOCR seems to work fine without any error messages.

**Comment by danpla** [comment]
I assume the issue is related to your local configuration. Most likely, it's an incorrect path in the TESSDATA_PREFIX environment variable. 

On Unix-like systems, it's best to ensure that TESSDATA_PREFIX is not set, which will let Tesseract pick the correct data path automatically.
