### ISSUE TITLE
Using Tesseract 4 languages with Tesseract 5

### ISSUE THREAD

**Issue by vivadavid** [danpla/dpscreenocr#21]
Hi,

I've downloaded version 1.1.0, which supports Tesseract 5.2.0, but OCR languages refer to Tesseract 4.1:

https://danpla.github.io/dpscreenocr/languages

I'm particularly interested in Spanish.

Thanks in advance and thank you for your programme!

**Comment by danpla** [comment]
Hi,

Both Tesseract 4 and 5 use the same language file format. Despite "4.1.0" in URLs, these are the most recent files in [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast) ar the moment.

**Comment by vivadavid** [comment]
> Hi,
> 
> Both Tesseract 4 and 5 use the same language file format. Despite "4.1.0" in URLs, these are the most recent files in [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast) at the moment.

Thank you, @danpla
