### ISSUE TITLE
Cannot install english language

### ISSUE THREAD

**Issue by sanjarcode** [danpla/dpscreenocr#22]
After installation using the PPA, I installed `tesseract-ocr-eng`, but it wasn't recognized. So I reinstalled the app. Still does not recognize language.

This is very bad UX, and no examples for English packages are given in the manual.

I'm on Ubuntu 20.04

**Comment by danpla** [comment]
Do you have the TESSDATA_PREFIX environment variable set (does `echo $TESSDATA_PREFIX` prints something)?

**Comment by danpla** [comment]
You can also check whether the command-line `tesseract` tool works correctly.

**Comment by danpla** [comment]
I was unable to reproduce the issue. I'm closing it due to lack of feedback; feel free to reopen it if you have anything to add.
