### ISSUE TITLE
Issues with vertical Japanese text

### ISSUE THREAD

**Issue by toprak** [danpla/dpscreenocr#25]
sorry if its stupid, I read the manual or doc whatever you call but I could not decide should I use split text block or not, im using dpscreenocr for manga reading, ty.

**Comment by danpla** [comment]
Thanks for your question. Answering to your question directly: as far as I can tell, it should not make a difference with vertical Japanese text.

However, thanks to your question, I found some issues in the current version of dpScreenOCR (1.3.0) regarding vertical Japanese text (`jpn_vert` and potentially other languages that support vertical text, like `chi_sim_vert` and `kor_vert`). I will fix them in the next release, but for now the situation is this:

* On Linux, dpScreenOCR can only recognize vertical Japanese text if "Split text blocks" is enabled.
* On Windows, recognition of vertical Japanese text is unfortunately completely broken in the current version, regardless of the "Split text blocks" option.

So, if you are using Windows, you can either switch to another OCR program (e.g. Capture2Text) or wait for the next version of dpScreenOCR.

**Comment by danpla** [comment]
The fix was made both on dpScreenOCR  (74227e14405697897f19ddf1eb24b3c7cdc310ad) and Tesseract (tesseract-ocr/tesseract/issues/3997) sides, and will be available in the next dpScreenOCR version.
