### ISSUE TITLE
add-apt-repository: The repository [...]  does not have a Release file

### ISSUE THREAD

**Issue by claws99** [danpla/dpscreenocr#31]
```
$sudo add-apt-repository ppa:daniel.p/dpscreenocr

E: The repository 'https://ppa.launchpadcontent.net/daniel.p/dpscreenocr/ubuntu kinetic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

$sudo apt install  dpscreenocr
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package dpscreenocr
```

**Comment by danpla** [comment]
The repository currently only provides packages for long-term support (LTS) releases; Kinetic is not an LTS release. You can try to use a DEB package for the nearest LTS release (Jammy in your case) from the [packages](https://launchpad.net/~daniel.p/+archive/ubuntu/dpscreenocr/+packages) page, or build the program manually as described in the user manual.

**Comment by claws99** [comment]
I tried building from source by following the build instructions

I get the error when I run the program. No clue what to do.
![](https://i.imgur.com/KslH1jL.png)

**Comment by claws99** [comment]
> You can try to use a DEB package for the nearest LTS release (Jammy in your case) from the [packages](https://launchpad.net/~daniel.p/+archive/ubuntu/dpscreenocr/+packages) page,


I tried this but I am getting the error saying "unmet dependencies"

**Comment by danpla** [comment]
> I get the error when I run the program. No clue what to do.

On your login screen, after you choose the user and the password appears, there should be a gear button that lets you choose X11 (Xorg) session.

If you use a distro other than Ubuntu, the things may be a bit different, but in general there should be an option that allows you to choose Xorg on login.

**Comment by danpla** [comment]
The PPA now has builds for non-LTS releases. Not for Kinetic, however, as it reached the end of life, but for Lunar and newer. Run:
```
sudo apt update
sudo apt install dpscreenocr
```
