### ISSUE TITLE
Does dpscreenocr do postprocessing

### ISSUE THREAD

**Issue by toprak** [danpla/dpscreenocr#37]
I'm trying to find ways to improve OCR quality so I have seen some OCR postprocess tweaking with imagemagick so I wonder do dpscreenocr that already?

**Comment by danpla** [comment]
Yes, it scales image x4 times using Catmul-Rom interpolation and then applies unsharp masking with radius 10 and amount 1.

**Comment by toprak** [comment]
@danpla Thank you!

**Comment by danpla** [comment]
You're welcome!
