### ISSUE TITLE
I can't set Capslock as cancel selection

### ISSUE THREAD

**Issue by toprak** [danpla/dpscreenocr#38]
I tried to add these to config file `Caps`, `Capslock`, `Caps-Lock`, `CapsLock` but it does not work after restarting dpscreenocr hotkey_cancel_selection is being empty

**Comment by danpla** [comment]
That's intentional: the lock keys - Caps, Num, and Scroll - are not available for hotkeys. You can only use the keys available from the drop-down menu.
