### ISSUE TITLE
Show popup window with result text 

### ISSUE THREAD

**Issue by MurzNN** [danpla/dpscreenocr#4]
At now result of OCR operation seem placed only in history textarea, so not easy to understand that process successfully completed. Will be good to show popup window with result text after finishing recognize process.

**Comment by MurzNN** [comment]
This already can be done via exec custom command feature (eg `kdialog`), but this is not so easy task for regular users, so simple checkbox in settings for enable result popups will be good feature.

**Comment by danpla** [comment]
I'm not sure such feature is useful.

A user normally wants to know when recognition is completed to make something with the text right after the completion (e.g. read it, copy, etc.). In this case, the interface is open and it's possible to see the progress. The progress is shown not only in the Main tab, but also in the window title, so you can see it even when the app is minimized.

Another problem is that you can queue several areas for OCR. Some of them may have a lot of text, which will take a significant time to recognize and will not fit to a popup; others may have just several words, and a series of such popups will immediately clutter your desktop.

I think any kind of notification mechanism just doesn't fit in the workflow the app is designed for.
