### ISSUE TITLE
Silent autostart (Linux Mint)

### ISSUE THREAD

**Issue by Mark3xtrm** [danpla/dpscreenocr#41]
At the moment, it seems that's not possible to start _dpscreenocr_ without having its window opened.
I don't need to use the window, I'd just want to use the ocr screenshot reading feature through the setted keyboard shortcut.

Also, and maybe obviously, I don't want to start the app manually, and so I'd be great if there was a "autostart at system startup" feature (with, like said before, no window opened and then showed).

**Comment by danpla** [comment]
dpScreenOCR currently doesn't have a checkbox "autostart at system startup", but you can always add it to the startup manually (https://community.linuxmint.com/tutorial/view/988). Then, edit the settings file as described in the [Tweaking](https://danpla.github.io/dpscreenocr/manual.html#tweaking) section of the user manual to enable the `ui_window_minimize_on_start` and `ui_window_minimize_to_tray` options, and you will get exactly the behavior you need.

**Comment by Mark3xtrm** [comment]
> dpScreenOCR currently doesn't have a checkbox "autostart at system startup", but you can always add it to the startup manually (https://community.linuxmint.com/tutorial/view/988). Then, edit the settings file as described in the [Tweaking](https://danpla.github.io/dpscreenocr/manual.html#tweaking) section of the user manual to enable the `ui_window_minimize_on_start` and `ui_window_minimize_to_tray` options, and you will get exactly the behavior you need.

My bad, I didn't pay attention to all the _Tweaking_ options. It does exactly what I wish, thanks, @danpla 🙏🏼
