### ISSUE TITLE
I've downloaded this for Ubuntu but can't get it to run

### ISSUE THREAD

**Issue by jrd656** [danpla/dpscreenocr#7]
I'm new to Ubuntu and have no idea where the download is saved or how to get the application to run. Can you please give some further guidance?

**Comment by danpla** [comment]
Run in terminal:
```
sudo add-apt-repository ppa:daniel.p/dpscreenocr
sudo apt-get update
sudo apt-get install dpscreenocr
```

**Comment by seltzered** [comment]
I've been trying to install this on Ubuntu 21.04 and am having trouble with the apt repo. @danpla what rev are you testing on?

my steps:
tried `sudo add-apt-repository ppa:daniel.p/dpscreenocr` 
apt returns 
```
E: The repository 'http://ppa.launchpad.net/daniel.p/dpscreenocr/ubuntu hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
I've tried `sudo apt-get update` with the  `--allow-insecure-repositories` but it doesn't seem to ignore the channel, i.e. it'll return `Ign:6 http://ppa.launchpad.net/daniel.p/dpscreenocr stable InRelease ` among other lines.

This means running `sudo apt-get install dpscreenocr` leads to the error: `E: Unable to locate package dpscreenocr`

**Comment by danpla** [comment]
At this moment, PPA doesn't have a build for Hirsute. In general, I'm trying to update PPA for LTS releases, but usually forget to do that for "normal" releases since they come out rather often (every six moths).

As a quick workaround, you can try to install a DEB for Focal: https://launchpad.net/~daniel.p/+archive/ubuntu/dpscreenocr/+build/19282217

**Comment by danpla** [comment]
@seltzered The PPA now has builds for non-LTS releases. Of course, not for Hirsuite or other versions that reached the end of life, but for Lunar and newer.
