### ISSUE TITLE
Wont show up on Windows 10

### ISSUE THREAD

**Issue by tado888** [danpla/dpscreenocr#9]
![image](https://user-images.githubusercontent.com/66261991/83418772-b50ea500-a456-11ea-88ee-27a25644cc6f.png)
![image](https://user-images.githubusercontent.com/66261991/83418790-bb9d1c80-a456-11ea-90bc-c481705391f6.png)

It wont show up. I already placed the language in the correct folder. English language.

**Comment by danpla** [comment]
The window doesn't appear, right?

Can you tell your Windows' version and whether the program was installed via the exe installer or ZIP package?

**Comment by tado888** [comment]
Win 10 64 bit
I tried both

**Comment by danpla** [comment]
Is the window initially white when you launch the app or it becomes so after you minimize/show it?

**Comment by danpla** [comment]
I was unable to reproduce the problem on Windows 10 version 1909 build 18363.592.

Can you tell your Windows' 10 version and OS build number? You can find them in Settings -> System -> About.

**Comment by clach04** [comment]
Microsoft Windows [Version 10.0.19042.1110]

Works for me (from installer)

**Comment by danpla** [comment]
@tado888, please try the version 1.1.0. If the problem still exists, feel free to reopen the issue.
